### ISSUE TITLE
[feature request] Overcharge Threshold Notification

### ISSUE THREAD

**Issue by kernicek** [jurassicplayer/decky-autosuspend#2]
Hi,

do you think it would be possible to add a notification when the battery charges to a given percentage? I like to keep my deck between 30% and 70% charge when possible to make the battery last as long as possible in the long term, but sometimes when playing and charging, I don't notice that I've passed 70%. This would really help me a lot.

Thank you!
Vojta

**Comment by jurassicplayer** [comment]
@kernicek 
Overcharging threshold has been added in v1.3.0. You can follow the manual installation instructions or just wait until it is added to the decky plugin store.
By default, the overcharge threshold is disabled (since I don't use it personally), so in order to enable it, you will need to:
- Open the AutoSuspend menu
- Highlight anything on the AutoSuspend menu
- Press the hamburger button to toggle showing/hiding disabled thresholds
- Highlight the Overcharge Threshold and press X to enable
- Configure to your preferred settings
- Press `Apply Changes`

As a sidenote, I'm pretty sure SteamOS has things in place already to help users prolong their battery life (slow charging after 80% and discharging after 100% even while plugged in)

If it doesn't seem to work correctly, feel free to re-open or create a new issue detailing the problem.
