### ISSUE TITLE
[Feature] Sleep timer / play timer

### ISSUE THREAD

**Issue by OJ7** [jurassicplayer/decky-autosuspend#5]
**Is your feature request related to a problem? Please describe.**
Not sure if this should be part of this plugin or a separate one should be created, but it seems related enough. It would be nice to have a sleep timer such that the device auto suspends at a specific time (bed time). A warning can be issued 30 mins, 15 mins, 5 mins, 1 min, etc before suspending. This is similar to the parental controls setting on Nintendo Switch. 

Similarly, having a maximum play time setting per day which gives you notifications when reaching you play limit and auto suspends when reaching it (also from Nintendo Switch parental controls).

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by jurassicplayer** [comment]
Seems relatively feasible (tentative). I probably won't implement quite so many warning notifications. One warning, maybe two max, at like 10-15 minutes left gives a reasonable amount of time to wrap up things. Not really useful as a parental control feature since at the moment, nothing is stopping anyone from just enabling/disabling AutoSuspend's settings, but I can see people using it just as a reminder/restriction for themselves to abide/ignore.

Notes to self:
- BedtimeThreshold/PlaytimeThreshold?
- BedTimer and PlayTimer will probably need separate tracking to prevent messing with each other
- BedTimer:
    - Pull current time
    - Reset flag on date != LastBedTimerSuspend (only date)
    - Trigger suspend on date time greater than threshold
    - Save new LastBedTimerSuspend to config
- PlayTimer:
    - On resume/boot
        - Load LastPlayTimerSuspend and CurrentPlayTime
        - Set SessionStartTime to current timestamp
    - Within logic loop:
        - Use same pulled current time as BedTimer
        - Reset flag, SessionStartTime, and CurrentPlayTime on date != LastPlayTimerSuspend (only date)
        - Trigger suspend on currentTime - SessionStartTime + CurrentPlayTime  greater than threshold
        - Save LastPlayTimerSuspend to config
    - On NonPlayTimer suspend (if PlayTimer disabled, don't change CurrentPlayTime):
        - Save currentTime - SessionStartTime + CurrentPlayTime to config as new CurrentPlayTime

**Comment by jurassicplayer** [comment]
Thought I'd give an update since I've finally gotten around to revamping things. There isn't any release yet, but currently:
- Bedtime alarm logic is implemented
- Playtime...not implemented yet since it's a slightly more complicated one to keep track of.
- The number of alarms isn't locked to the pre-defined 3 (warning/critical/overcharge) anymore, instead the number of alarms is uncapped, and each individual alarm will be configurable (discharge/overcharge/bedtime)
- I've also implemented an idea of triggerActions (suspend/none atm) that is part of the individual alarm configuration, which maybe can be extended to have other actions (thinking of the lock screen, but haven't actually looked into the feasibility of this one)

**Comment by jurassicplayer** [comment]
So I've finally got around to at least the major stuff needed and pushed some things off for later releases to at least get something out. AutoSuspend v2.0.0 should have everything you need to at least satisfy this issue. Feel free to try it out from the download in releases, or wait until it reaches the decky testing/default store channel and re-open this issue if you run into any problems.
